[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; La velocidad del Monitor Serial (¡Súper importante que coincida con tu código!)
monitor_speed = 115200

; Las librerías que PlatformIO descargará automáticamente de internet
lib_deps = 
	olikraus/U8g2
	adafruit/Adafruit BME680 Library
	adafruit/Adafruit Unified Sensor